vector_db:
 collection_name: "research_documents"

embedding:
 provider: "google"
 model_name: "models/text-embedding-004"

retrivers:
 top_k: 10

llm:
 groq:
  provider: "groq"
  model_name: "llama-3.1-8b-instant"
  temperature: 0
  max_tokens: 2048

 google:
  provider: "google"
  model_name: "gemini-2.0-flash"
  temperature: 0
  max_output_tokens: 2048

 openai:
  provider: "openai"
  model_name: "gpt-4o"
  
  